services:
  container-a:
    build:
      context: ./container-a
    volumes:
      - ../metrics:/metrics
    environment:
      - PIPELINE_NAME=Container_A_Lightweight
      - EPOCHS=10
      - BATCH_SIZE=16
    restart: "no"

  container-b:
    build:
      context: ./container-b
    volumes:
      - ../metrics:/metrics
    environment:
      - PIPELINE_NAME=Container_B_Advanced
      - EPOCHS=15
      - BATCH_SIZE=16
      - K_FOLDS=5
    restart: "no"
